### ISSUE TITLE
Example in the README does not work

### ISSUE THREAD

**Issue by mrmlnc** [pugjs/pug-source-gen#5]
Hello,

I copied the example from the README file and got the error at startup with Node.js **v6.1.0**.

```
C:\projects\test\node_modules\pug-source-gen\lib\code-generator.js:224
      throw new TypeError(msg);
      ^

TypeError: A child of Block (Pug:2) is of type RawInclude, which is not supported by pug-source-gen.
    at Object.CodeGenerator.visit (C:\projects\test\node_modules\pug-source-gen\lib\code-generator.js:224:13)
    at Object.<anonymous> (C:\projects\test\node_modules\pug-source-gen\lib\code-generator.js:285:12)
    at Array.forEach (native)
    at Object.CodeGenerator.visitBlock (C:\projects\test\node_modules\pug-source-gen\lib\code-generator.js:284:17)
    at Object.CodeGenerator.visit (C:\projects\test\node_modules\pug-source-gen\lib\code-generator.js:227:30)
    at Object.CodeGenerator.compile (C:\projects\test\node_modules\pug-source-gen\lib\code-generator.js:25:10)
    at generateCode (C:\projects\test\node_modules\pug-source-gen\index.js:22:53)
    at Object.<anonymous> (C:\projects\test\i.js:21:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

**Comment by ForbesLindesay** [comment]
The example in the README is just a bare bones example.  You need to also use the loader and linker to support includes and filters to support filters.  You can see a full example with loading, linking, stripping of comments, handling filters, adding default file extensions to includes and extends etc. in the actual pug source code https://github.com/pugjs/pug/blob/master/lib/index.js#L56-L140

**Comment by TimothyGu** [comment]
What @ForbesLindesay was referring to was pug-code-gen, not pug-source-gen. This module is a bit unmaintained right now because of a lack of official use cases, but when I get some time I'll take a look again.

**Comment by mrmlnc** [comment]
Just i was inspired [Stylefmt](https://github.com/morishitter/stylefmt) and thought about creating _pugfmt_. Now i'm experimenting with building Pug syntax from tree pug-lexer and passed [24/114 tests](https://github.com/pugjs/pug/tree/master/test/cases).

However, i now realized that this generator is not suitable for my task. Because it does not preserve the original syntax. For example:

**Before pug-source-gen:**

``` jade
foo(abc
   ,def)
```

**After:**

``` jade
foo(abc def)
```

**Comment by TimothyGu** [comment]
I'll be happy to add a few tweaking options like whether commas are preserved, etc. But even mature source generators like Babel [cannot preserve newlines](https://babeljs.io/repl/#?evaluate=false&lineWrap=false&presets=&code=var%20a%0A%20%20%2C%20b%3B), so I think it is an unreasonable request for pug-source-gen to do so. I wrote this module more for testing, really, than anything else.

**Comment by ForbesLindesay** [comment]
Sorry,  failed to notice that this was a different rep :)

If this is to build an automated formatted we don't really need to preserve new lines, just atutomatically generate them when lines would be longer than some length deemed acceptable.

**Comment by mrmlnc** [comment]
Thanks for the answers :+1: 

I brought the example of multi-line attributes only for the sake of example. The idea of the split attributes to strings when it reaches a certain length sounds good.
